
import java.util.Scanner;

public class producerConsumer {

    public static int takeInput() {
        int num = -1;
        boolean haveNum = false;
        Scanner scanner = new Scanner(System.in);

        while (!haveNum) {
            System.out.println("Please enter a number: ");
            if (scanner.hasNextInt()) {
                //Read integer 
                num = scanner.nextInt();
                haveNum = true;
            } else {
                // If the input is not an integer, handle the error
                System.out.println("Invalid input. Please enter a valid integer.");
            }
                
            if (num < 0) {
                haveNum = false;
                System.out.println("Invalid input. Please enter a positive integer.");
            }
        }
        scanner.close();
        return num;
        
    }

    public static void main(String[] args) throws InterruptedException  {
        //Number of random numbers generated by producer 
        int numNums = -1;
        //create scanner 
        Scanner scanner = new Scanner(System.in);

        if (args.length > 0) {
            try {
                //try convert string to int 
                numNums = Integer.parseInt(args[0]);
                if (numNums < 0) 
                    numNums = takeInput();
            } catch (NumberFormatException e) {
                System.out.println("Error: The input is not a valid integer.");
            }
        } else {
            numNums = takeInput();
        }
        

       
        Thread producer = new Thread(new Producer(numNums), "Producer");  
        ArrayQueue queue = new ArrayQueue();
        queue
        producer.start();
        
            

        
    }
}


